random_seed = 42
learning_rate = 0.001
model_type = "Pytorch"
num_epochs = 1
batch_size = 32
num_rounds = 2
clients_per_round = 1

[model]
output_size = 10

[dataset]
name = "MNIST"
root = "./dataset/mnist"
validation_split = 0.2

[server.strategy]
name = "FedAvg"
fraction_fit = 1.0
fraction_evaluate = 1.0
min_fit_clients = 1
min_available_clients = 1
min_evaluate_clients = 1

[runtime]
manager_port = 8004
